name: CI/CD Pipeline - Pediguide - Preview

on:
  push:
    branches-ignore:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_TOKEN_PREVIEW: ${{ secrets.VERCEL_TOKEN_PREVIEW }}

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    environment: preview
    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_BACKEND_PROJECT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information (Backend)
        working-directory: ./backend
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN_PREVIEW }}

      - name: Build Backend Artifacts
        working-directory: ./backend
        run: vercel build --token=${{ secrets.VERCEL_TOKEN_PREVIEW }}
      - name: Deploy Backend to Production
        working-directory: ./backend
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN_PREVIEW }}

  deploy-frontend:
    needs: deploy-backend
    runs-on: ubuntu-latest
    environment: preview
    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_FRONTEND_PROJECT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information (Frontend)
        working-directory: ./frontend
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN_PREVIEW }}

      - name: Build Frontend Artifacts
        working-directory: ./frontend
        run: vercel build --token=${{ secrets.VERCEL_TOKEN_PREVIEW }}
      - name: Deploy Frontend to Production
        working-directory: ./frontend
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN_PREVIEW }}